name: Publish framework

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_OPTIONS: "--max_old_space_size=7000"
  PKG_DIR: packages/framework
  PKG_OUT: packages/framework/out

jobs:
  get-versions:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    outputs:
      previous-version: ${{ steps.previous-version.outputs.version }}
      updated-version: ${{ steps.updated-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get previous version
        id: previous-version
        uses: ./.github/actions/get-package-version
        with:
          sha: ${{ github.event.before }}
          pkg-dir: ${{ env.PKG_DIR }}
      - name: Get updated version
        id: updated-version
        uses: ./.github/actions/get-package-version
        with:
          sha: ${{ github.sha }}
          pkg-dir: ${{ env.PKG_DIR }}
      - name: Print result
        env:
          PREV: ${{ steps.previous-version.outputs.version }}
          UPDATED: ${{ steps.updated-version.outputs.version }}
        run: |
          echo Package directory: ${{ env.PKG_DIR }}
          echo Previous version: ${{ env.PREV }}
          echo Updated version: ${{ env.UPDATED }}

  publish:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: get-versions
    if: github.event_name != 'push'  || needs.get-versions.outputs.previous-version != needs.get-versions.outputs.updated-version
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run publish -- --filter @anvil-vault/framework
      # Append -{{ ref_name }} to version number if on not on production branch
      - name: Add pre-release flag
        if: github.ref_name != 'main'
        working-directory: ${{ env.PKG_OUT }}
        run: |
          full_version=$(echo "-${{ github.ref_name }}" | sed 's/\//-/g')
          jq --arg v "${full_version}" '.version += $v' package.json > tmp.json
          mv tmp.json package.json
      - name: Publish to registry pre-release
        if: github.ref_name != 'main'
        working-directory: ${{ env.PKG_OUT }}
        run: npm publish --tag ${{ github.ref_name }}
       
      - name: Publish to registry
        if: github.ref_name == 'main'
        working-directory: ${{ env.PKG_OUT }}
        run: npm publish
      
